#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: Yzg1ZjFjNTdkZDBkYzRhNDkyYmRjMjlkMTMwOWRlMTRjYjNjNGRlOWRmMzJlYzQ1ZjhjOWM0NmQ2MmU4MTM0ZTMyMjFjODU4NWJjYmY4ZTZlY2NmZGQzMTRhNWI4ZDA5OTZiMw==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
