# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MTgwMzIxYjE5OTBlMjY0YjlmY2MyODI0YTU2NWEyN2E4MzhmYjZjMDc5ZGI2MWM0MDdiYjQ3NzNjMzIzNzEyMWE2NDQ2M2VmNjRhODIxYzRmZjllYTg3NzJmMWVlNjk1N2RmZDM3NWFlY2M1MWNiYzIyN2I2YjljNjBlMzRhZmU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
